main:
  - identifier: home
    name: 首页
    url: /
    pre: home
    weight: 1
  - identifier: about
    name: 关于
    url: /about.html
    pre: user
    weight: 2
  - identifier: archives
    name: 归档
    url: /posts
    pre: archive
    weight: 3
  - identifier: commonweal
    name: 公益 404
    url: /404.html
    pre: heartbeat
    weight: 4