baseURL: https://hugo-next.eu.org
canonifyURLs: true
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "Hugo NexT"
theme: "hugo-theme-next"
metaDataFormat: "yaml"
algolia:
  index: "hugo-theme-next"
  key: "2c77d9c12b2363f7dd88ebeeb59d036f"
  appID: "1WD4PPLUFG"