name: Deploy Hugo NexT Docs Site

on:
  push:
    branches:
      - source

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 

      - name: Setting variable
        run: sh .github/scripts/replace-vars.sh

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.100.1'
          extended: true

      - name: Build Site
        run: hugo --minify

      - name: Copy README & License
        run: |
              cp README.md REDME.zh.md ./public
              cp LICENSE ./public

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          external_repository: hugo-next/hugo-next.github.io
          publish_dir: "./public"        
          keep_files: false
          publish_branch: main
          commit_message: ${{ github.event.head_commit.message }}